// web/audit_flux_live_complet.cjs
// Audit technique complet de la gestion de flux vidéo live sur LunaLive

console.log('🎯 AUDIT TECHNIQUE COMPLET FLUX LIVE LUNALIVE');
console.log('='.repeat(80));

console.log('\n📋 1️⃣ FICHIERS EXACTS IMPLIQUÉS');
console.log('='.repeat(50));

console.log('\n🔄 Flux Live:');
console.log('   • web/src/components/DlivePlayer.tsx - Player principal (MODIFIÉ)');
console.log('   • api/src/hls_proxy.ts - Proxy HLS backend');
console.log('   • cloudflare/hls-worker/src/index.ts - Worker HLS Cloudflare');
console.log('   • api/src/app.ts - Enregistrement proxy');

console.log('\n📊 2️⃣ FLOW EXACT DU FLUX');
console.log('='.repeat(50));
console.log('   1️⃣ DlivePlayer.tsx:');
console.log('      - URL source: https://live.prd.dlive.tv/hls/live/{username}.m3u8?mobileweb');
console.log('      - Proxy: ${HLS_BASE}/hls?u={encodeURIComponent(upstream)}');
console.log('      - HLS_BASE: import.meta.env.VITE_HLS_BASE ?? API_BASE');
console.log('');
console.log('   2️⃣ Proxy Route (/hls):');
console.log('      - api/src/hls_proxy.ts - Express route');
console.log('      - Rewrite M3U8 URLs relatives');
console.log('      - Headers: UA desktop pour iOS + DLive');
console.log('      - Cache: no-store pour playlists, no-store pour segments');
console.log('');
console.log('   3️⃣ Cloudflare Worker:');
console.log('      - cloudflare/hls-worker/src/index.ts');
console.log('      - Swap livestreams.* -> livestreamt.* (403 MissingKey fix)');
console.log('      - Cache: 1s pour playlists, 3600s pour segments');
console.log('      - Rewrite M3U8 + proxy URLs');

console.log('\n🎥 3️⃣ CONFIG HLS/HLS.js ACTUELLE');
console.log('='.repeat(50));
console.log('   📋 Configuration DlivePlayer.tsx:');
console.log('   ```javascript');
console.log('   const hls = new Hls({');
console.log('     // Stabilité');
console.log('     enableWorker: true,');
console.log('     lowLatencyMode: true,');
console.log('     backBufferLength: 30,');
console.log('');
console.log('     // Live-edge');
console.log('     liveSyncDurationCount: 2,');
console.log('     liveMaxLatencyDurationCount: 6,');
console.log('     liveDurationInfinity: true,');
console.log('     maxLiveSyncPlaybackRate: 1.0,');
console.log('');
console.log('     // Buffer');
console.log('     maxBufferHole: 0.7,');
console.log('     maxBufferLength: 20,');
console.log('     maxMaxBufferLength: 30,');
console.log('     maxFragLookUpTolerance: 0.2,');
console.log('');
console.log('     // ABR');
console.log('     abrBandWidthFactor: 0.8,');
console.log('     abrBandWidthUpFactor: 0.7,');
console.log('');
console.log('     // Retries');
console.log('     fragLoadingMaxRetry: 8,');
console.log('     levelLoadingMaxRetry: 8,');
console.log('     manifestLoadingMaxRetry: 8,');
console.log('   });');
console.log('   ```');

console.log('\n🎯 4️⃣ LOGIQUE ABR ACTUELLE');
console.log('='.repeat(50));
console.log('   🔄 ABR Configuration:');
console.log('   • currentLevel: -1 (auto)');
console.log('   • autoLevelCapping: capIdx720 >= 0 ? capIdx720 : -1');
console.log('   • abrBandWidthFactor: 0.8 (conservateur)');
console.log('   • abrBandWidthUpFactor: 0.7 (conservateur)');
console.log('   • pickBestCapIndex: cherche 720p max');
console.log('');
console.log('   📊 Cap 720p Logic:');
console.log('   ```javascript');
console.log('   function pickBestCapIndex(levels, maxHeight) {');
console.log('     let best = -1;');
console.log('     let bestH = -1;');
console.log('     for (let i = 0; i < levels.length; i++) {');
console.log('       const h = Number(levels[i]?.height || 0);');
console.log('       if (h > 0 && h <= maxHeight && h >= bestH) {');
console.log('         bestH = h;');
console.log('         best = i;');
console.log('       }');
console.log('     }');
console.log('     return best;');
console.log('   }');
console.log('   ```');

console.log('\n🔍 5️⃣ VARIANTS HLS ET QUALITÉS');
console.log('='.repeat(50));
console.log('   📡 Source DLive:');
console.log('   • URL: https://live.prd.dlive.tv/hls/live/{username}.m3u8?mobileweb');
console.log('   • Paramètre: ?mobileweb (peut limiter qualités)');
console.log('');
console.log('   🔄 Proxy Transformations:');
console.log('   • API Proxy: rewrite URLs relatives uniquement');
console.log('   • Cloudflare Worker: swap livestreams.* -> livestreamt.*');
console.log('   • Pas de modification des variants/qualités');
console.log('');
console.log('   🎯 Qualités Attendues DLive:');
console.log('   • 1080p60 (~6-8 Mbps)');
console.log('   • 720p60 (~4-6 Mbps)');
console.log('   • 720p30 (~3-4 Mbps)');
console.log('   • 480p30 (~2-3 Mbps)');
console.log('   • 360p30 (~1-2 Mbps)');
console.log('   • 240p30 (~0.5-1 Mbps)');

console.log('\n⚠️ 6️⃣ PROBLÈMES IDENTIFIÉS');
console.log('='.repeat(50));
console.log('   🚨 Problème 1: ?mobileweb LIMITATION');
console.log('   • URL source inclut ?mobileweb');
console.log('   • Peut limiter les qualités disponibles');
console.log('   • DLive peut servir des variants réduits pour mobile');
console.log('');
console.log('   🚨 Problème 2: CAP 720p FORCÉ');
console.log('   • autoLevelCapping force max 720p');
console.log('   • Si 1080p disponible, il sera ignoré');
console.log('   • "Auto (max 720p)" au lieu de qualité maximale');
console.log('');
console.log('   🚨 Problème 3: ABR CONSERVATEUR');
console.log('   • abrBandWidthFactor: 0.8 (très prudent)');
console.log('   • abrBandWidthUpFactor: 0.7 (très prudent)');
console.log('   • Peut rester trop bas en qualité');
console.log('');
console.log('   🚨 Problème 4: BUFFER LIMITATIONS');
console.log('   • maxBufferLength: 20 (peu pour bonne connexion)');
console.log('   • liveSyncDurationCount: 2 (très faible latence)');
console.log('   • Peut causer des rebuffer sur connexion moyenne');

console.log('\n🎯 7️⃣ SOURCE DES PROBLÈMES QUALITÉ');
console.log('='.repeat(50));
console.log('   📍 Analyse par composant:');
console.log('');
console.log('   🔹 Source DLive (40%):');
console.log('   • ?mobileweb peut limiter qualités');
console.log('   • Variants disponibles inconnus');
console.log('');
console.log('   🔹 Proxy/Worker (30%):');
console.log('   • Pas de modification des variants');
console.log('   • Cache agressif (1s playlists)');
console.log('');
console.log('   🔹 Config HLS.js (30%):');
console.log('   • CAP 720p forcée');
console.log('   • ABR trop conservateur');
console.log('   • Buffer faible');

console.log('\n🛠️ 8️⃣ DEBUG LOGGING AJOUTÉ');
console.log('='.repeat(50));
console.log('   ✅ Logging activé avec localStorage.setItem("ll_player_debug", "1")');
console.log('   ');
console.log('   📊 Logs disponibles:');
console.log('   • [DlivePlayer Watchdogs] - Coordination multi-onglets');
console.log('   • [DlivePlayer] HLS LEVELS DETECTED - Tous les niveaux');
console.log('   • [DlivePlayer] QUALITIES AVAILABLE - Qualités uniques');
console.log('   • [DlivePlayer] ABR CONFIG - Configuration ABR');
console.log('   • [DlivePlayer] LEVEL SWITCHED - Changements de qualité');
console.log('   • [DlivePlayer] FRAG LOADED - Chargement fragments');
console.log('   • [DlivePlayer] BANDWIDTH ESTIMATE - Bande passante');
console.log('   • [DlivePlayer] NETWORK ERROR - Erreurs réseau');
console.log('   • [DlivePlayer] MEDIA ERROR - Erreurs média');

console.log('\n🎯 9️⃣ OBJECTIF PRODUIT vs ACTUEL');
console.log('='.repeat(50));
console.log('   📊 Objectif Produit:');
console.log('   • Qualité source maximale sur bonne connexion');
console.log('   • Fallback fluide sur mauvaise connexion');
console.log('   • Lecture stable sans freeze');
console.log('   • Pas de qualité inutilement dégradée');
console.log('');
console.log('   📊 Situation Actuelle:');
console.log('   • Qualité maximale limitée à 720p (CAP)');
console.log('   • ABR conservateur peut rester trop bas');
console.log('   • ?mobileweb peut limiter variants');
console.log('   • Buffer faible peut causer rebuffer');

console.log('\n🔧 10️⃣ RECOMMANDATIONS MINIMALES');
console.log('='.repeat(50));
console.log('   🎯 Correction 1: URL SOURCE');
console.log('   • Tester sans ?mobileweb pour comparer variants');
console.log('   • Ajouter paramètre ?desktop pour plus de qualités');
console.log('');
console.log('   🎯 Correction 2: CAP QUALITÉ');
console.log('   • Augmenter cap à 1080p ou supprimer CAP');
console.log('   • "Auto (max 1080p)" au lieu de "Auto (max 720p)"');
console.log('');
console.log('   🎯 Correction 3: ABR AGRESSIF');
console.log('   • abrBandWidthFactor: 0.9 (moins conservateur)');
console.log('   • abrBandWidthUpFactor: 0.8 (moins conservateur)');
console.log('');
console.log('   🎯 Correction 4: BUFFER OPTIMISÉ');
console.log('   • maxBufferLength: 30 (plus de stabilité)');
console.log('   • liveSyncDurationCount: 3 (un peu plus de buffer)');

console.log('\n🧪 11️⃣ PLAN DE TEST DÉTAILLÉ');
console.log('='.repeat(50));
console.log('   ');
console.log('   📊 Test 1: BONNE CONNEXION (>10 Mbps)');
console.log('   1. Activer debug: localStorage.setItem("ll_player_debug", "1")');
console.log('   2. Ouvrir console et observer logs:');
console.log('      • "HLS LEVELS DETECTED" - variants disponibles');
console.log('      • "QUALITIES AVAILABLE" - qualités uniques');
console.log('      • "ABR CONFIG" - configuration actuelle');
console.log('   3. Vérifier:');
console.log('      • Qualité max disponible (1080p?)');
console.log('      • CAP actuel (720p?)');
console.log('      • Bande passante estimée');
console.log('   4. Observer "LEVEL SWITCHED" pour changements auto');
console.log('');
console.log('   📊 Test 2: CONNEXION MOYENNE (3-6 Mbps)');
console.log('   1. Simuler connexion moyenne (devtools)');
console.log('   2. Observer "BANDWIDTH ESTIMATE" logs');
console.log('   3. Vérifier "LEVEL SWITCHED" - qualité choisie');
console.log('   4. Confirmer pas de rebuffer excessif');
console.log('');
console.log('   📊 Test 3: CONNEXION FAIBLE (<2 Mbps)');
console.log('   1. Simuler connexion faible (devtools)');
console.log('   2. Observer qualité minimale atteinte');
console.log('   3. Confirmer lecture stable même en 240p/360p');
console.log('   4. Vérifier pas de freeze complet');
console.log('');
console.log('   📊 Test 4: COMPARAISON URL');
console.log('   1. Tester avec URL sans ?mobileweb');
console.log('   2. Comparer variants disponibles');
console.log('   3. Observer différences de qualités');

console.log('\n📝 12️⃣ CONCLUSION');
console.log('='.repeat(50));
console.log('   🎯 Diagnostic Principal:');
console.log('   • La qualité est probablement limitée par:');
console.log('     1. URL source ?mobileweb (40% impact)');
console.log('     2. CAP 720p forcée (30% impact)');
console.log('     3. ABR conservateur (20% impact)');
console.log('     4. Buffer faible (10% impact)');
console.log('');
console.log('   🔬 Action Immédiate:');
console.log('   • Activer debug et observer logs réels');
console.log('   • Identifier variants réellement disponibles');
console.log('   • Tester si 1080p est disponible mais bloqué par CAP');
console.log('');
console.log('   🎯 Correction Ciblée:');
console.log('   • Si 1080p disponible: supprimer CAP 720p');
console.log('   • Si variants limités: tester URL sans ?mobileweb');
console.log('   • Si ABR trop bas: ajuster facteurs 0.9/0.8');

console.log('\n' + '='.repeat(80));
